# Generated by Django 4.2.7 on 2026-07-17 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cafeteriamenu_cafeteriaorder_hostel_transportroute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Aquatic', 'Aquatic'), ('Combat', 'Combat'), ('Athletics', 'Athletics')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('coach_name', models.CharField(blank=True, max_length=200)),
                ('coach_phone', models.CharField(blank=True, max_length=15)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('max_team_size', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sports',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tournament_type', models.CharField(choices=[('Intra College', 'Intra College'), ('Inter College', 'Inter College'), ('District', 'District'), ('State', 'State'), ('National', 'National')], default='Intra College', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='core.sport')),
            ],
            options={
                'db_table': 'tournaments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SportAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('College', 'College Level'), ('District', 'District Level'), ('State', 'State Level'), ('National', 'National Level'), ('International', 'International Level')], max_length=20)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('achievement_date', models.DateField()),
                ('certificate_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.sport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_achievements', to='core.student')),
            ],
            options={
                'db_table': 'sport_achievements',
                'ordering': ['-achievement_date'],
            },
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_role', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Internship', 'Internship'), ('Part Time', 'Part Time')], default='Full Time', max_length=50)),
                ('package_lpa', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('stipend_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('eligible_departments', models.CharField(blank=True, help_text='Comma separated dept codes', max_length=200)),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('max_backlogs', models.PositiveIntegerField(default=0)),
                ('drive_date', models.DateField()),
                ('last_apply_date', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20)),
                ('total_openings', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='core.company')),
            ],
            options={
                'db_table': 'placement_drives',
                'ordering': ['-drive_date'],
            },
        ),
        migrations.CreateModel(
            name='PlacementApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Offer Accepted', 'Offer Accepted'), ('Offer Declined', 'Offer Declined')], default='Applied', max_length=30)),
                ('resume_url', models.URLField(blank=True)),
                ('package_offered', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_applications', to='core.student')),
            ],
            options={
                'db_table': 'placement_applications',
                'ordering': ['-applied_date'],
                'unique_together': {('student', 'drive')},
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('Technical', 'Technical'), ('HR', 'HR'), ('Group Discussion', 'Group Discussion'), ('Aptitude Test', 'Aptitude Test'), ('Final', 'Final Round')], max_length=30)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('venue', models.CharField(blank=True, max_length=300)),
                ('interviewer', models.CharField(blank=True, max_length=200)),
                ('result', models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.placementapplication')),
            ],
            options={
                'db_table': 'interview_schedules',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='SportParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Confirmed', 'Confirmed'), ('Withdrawn', 'Withdrawn'), ('Disqualified', 'Disqualified')], default='Registered', max_length=20)),
                ('team_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_participations', to='core.student')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.tournament')),
            ],
            options={
                'db_table': 'sport_participations',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'tournament')},
            },
        ),
    ]
